// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: matrixDouble.proto

package protobuf;

public final class MatrixDouble {
  private MatrixDouble() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DRowOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 rowNum = 1;
    /**
     * <code>required int64 rowNum = 1;</code>
     */
    boolean hasRowNum();
    /**
     * <code>required int64 rowNum = 1;</code>
     */
    long getRowNum();

    // repeated double num = 2;
    /**
     * <code>repeated double num = 2;</code>
     */
    java.util.List<java.lang.Double> getNumList();
    /**
     * <code>repeated double num = 2;</code>
     */
    int getNumCount();
    /**
     * <code>repeated double num = 2;</code>
     */
    double getNum(int index);
  }
  /**
   * Protobuf type {@code protobuf.DRow}
   */
  public static final class DRow extends
      com.google.protobuf.GeneratedMessage
      implements DRowOrBuilder {
    // Use DRow.newBuilder() to construct.
    private DRow(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DRow(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DRow defaultInstance;
    public static DRow getDefaultInstance() {
      return defaultInstance;
    }

    public DRow getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DRow(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              rowNum_ = input.readInt64();
              break;
            }
            case 17: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                num_ = new java.util.ArrayList<java.lang.Double>();
                mutable_bitField0_ |= 0x00000002;
              }
              num_.add(input.readDouble());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                num_ = new java.util.ArrayList<java.lang.Double>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                num_.add(input.readDouble());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          num_ = java.util.Collections.unmodifiableList(num_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.MatrixDouble.internal_static_protobuf_DRow_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.MatrixDouble.internal_static_protobuf_DRow_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.MatrixDouble.DRow.class, protobuf.MatrixDouble.DRow.Builder.class);
    }

    public static com.google.protobuf.Parser<DRow> PARSER =
        new com.google.protobuf.AbstractParser<DRow>() {
      public DRow parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DRow(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DRow> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 rowNum = 1;
    public static final int ROWNUM_FIELD_NUMBER = 1;
    private long rowNum_;
    /**
     * <code>required int64 rowNum = 1;</code>
     */
    public boolean hasRowNum() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 rowNum = 1;</code>
     */
    public long getRowNum() {
      return rowNum_;
    }

    // repeated double num = 2;
    public static final int NUM_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Double> num_;
    /**
     * <code>repeated double num = 2;</code>
     */
    public java.util.List<java.lang.Double>
        getNumList() {
      return num_;
    }
    /**
     * <code>repeated double num = 2;</code>
     */
    public int getNumCount() {
      return num_.size();
    }
    /**
     * <code>repeated double num = 2;</code>
     */
    public double getNum(int index) {
      return num_.get(index);
    }

    private void initFields() {
      rowNum_ = 0L;
      num_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasRowNum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, rowNum_);
      }
      for (int i = 0; i < num_.size(); i++) {
        output.writeDouble(2, num_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, rowNum_);
      }
      {
        int dataSize = 0;
        dataSize = 8 * getNumList().size();
        size += dataSize;
        size += 1 * getNumList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protobuf.MatrixDouble.DRow parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.MatrixDouble.DRow parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.MatrixDouble.DRow parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.MatrixDouble.DRow parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.MatrixDouble.DRow parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.MatrixDouble.DRow parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protobuf.MatrixDouble.DRow parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protobuf.MatrixDouble.DRow parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protobuf.MatrixDouble.DRow parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.MatrixDouble.DRow parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobuf.MatrixDouble.DRow prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.DRow}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protobuf.MatrixDouble.DRowOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.MatrixDouble.internal_static_protobuf_DRow_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.MatrixDouble.internal_static_protobuf_DRow_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.MatrixDouble.DRow.class, protobuf.MatrixDouble.DRow.Builder.class);
      }

      // Construct using protobuf.MatrixDouble.DRow.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        rowNum_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        num_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.MatrixDouble.internal_static_protobuf_DRow_descriptor;
      }

      public protobuf.MatrixDouble.DRow getDefaultInstanceForType() {
        return protobuf.MatrixDouble.DRow.getDefaultInstance();
      }

      public protobuf.MatrixDouble.DRow build() {
        protobuf.MatrixDouble.DRow result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.MatrixDouble.DRow buildPartial() {
        protobuf.MatrixDouble.DRow result = new protobuf.MatrixDouble.DRow(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.rowNum_ = rowNum_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          num_ = java.util.Collections.unmodifiableList(num_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.num_ = num_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.MatrixDouble.DRow) {
          return mergeFrom((protobuf.MatrixDouble.DRow)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.MatrixDouble.DRow other) {
        if (other == protobuf.MatrixDouble.DRow.getDefaultInstance()) return this;
        if (other.hasRowNum()) {
          setRowNum(other.getRowNum());
        }
        if (!other.num_.isEmpty()) {
          if (num_.isEmpty()) {
            num_ = other.num_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureNumIsMutable();
            num_.addAll(other.num_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRowNum()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.MatrixDouble.DRow parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.MatrixDouble.DRow) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 rowNum = 1;
      private long rowNum_ ;
      /**
       * <code>required int64 rowNum = 1;</code>
       */
      public boolean hasRowNum() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 rowNum = 1;</code>
       */
      public long getRowNum() {
        return rowNum_;
      }
      /**
       * <code>required int64 rowNum = 1;</code>
       */
      public Builder setRowNum(long value) {
        bitField0_ |= 0x00000001;
        rowNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 rowNum = 1;</code>
       */
      public Builder clearRowNum() {
        bitField0_ = (bitField0_ & ~0x00000001);
        rowNum_ = 0L;
        onChanged();
        return this;
      }

      // repeated double num = 2;
      private java.util.List<java.lang.Double> num_ = java.util.Collections.emptyList();
      private void ensureNumIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          num_ = new java.util.ArrayList<java.lang.Double>(num_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated double num = 2;</code>
       */
      public java.util.List<java.lang.Double>
          getNumList() {
        return java.util.Collections.unmodifiableList(num_);
      }
      /**
       * <code>repeated double num = 2;</code>
       */
      public int getNumCount() {
        return num_.size();
      }
      /**
       * <code>repeated double num = 2;</code>
       */
      public double getNum(int index) {
        return num_.get(index);
      }
      /**
       * <code>repeated double num = 2;</code>
       */
      public Builder setNum(
          int index, double value) {
        ensureNumIsMutable();
        num_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double num = 2;</code>
       */
      public Builder addNum(double value) {
        ensureNumIsMutable();
        num_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double num = 2;</code>
       */
      public Builder addAllNum(
          java.lang.Iterable<? extends java.lang.Double> values) {
        ensureNumIsMutable();
        super.addAll(values, num_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double num = 2;</code>
       */
      public Builder clearNum() {
        num_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.DRow)
    }

    static {
      defaultInstance = new DRow(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuf.DRow)
  }

  public interface DMatrixOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 id = 1;
    /**
     * <code>required int64 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int64 id = 1;</code>
     */
    long getId();

    // repeated .protobuf.DRow row = 2;
    /**
     * <code>repeated .protobuf.DRow row = 2;</code>
     */
    java.util.List<protobuf.MatrixDouble.DRow> 
        getRowList();
    /**
     * <code>repeated .protobuf.DRow row = 2;</code>
     */
    protobuf.MatrixDouble.DRow getRow(int index);
    /**
     * <code>repeated .protobuf.DRow row = 2;</code>
     */
    int getRowCount();
    /**
     * <code>repeated .protobuf.DRow row = 2;</code>
     */
    java.util.List<? extends protobuf.MatrixDouble.DRowOrBuilder> 
        getRowOrBuilderList();
    /**
     * <code>repeated .protobuf.DRow row = 2;</code>
     */
    protobuf.MatrixDouble.DRowOrBuilder getRowOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code protobuf.DMatrix}
   */
  public static final class DMatrix extends
      com.google.protobuf.GeneratedMessage
      implements DMatrixOrBuilder {
    // Use DMatrix.newBuilder() to construct.
    private DMatrix(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DMatrix(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DMatrix defaultInstance;
    public static DMatrix getDefaultInstance() {
      return defaultInstance;
    }

    public DMatrix getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DMatrix(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                row_ = new java.util.ArrayList<protobuf.MatrixDouble.DRow>();
                mutable_bitField0_ |= 0x00000002;
              }
              row_.add(input.readMessage(protobuf.MatrixDouble.DRow.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          row_ = java.util.Collections.unmodifiableList(row_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.MatrixDouble.internal_static_protobuf_DMatrix_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.MatrixDouble.internal_static_protobuf_DMatrix_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.MatrixDouble.DMatrix.class, protobuf.MatrixDouble.DMatrix.Builder.class);
    }

    public static com.google.protobuf.Parser<DMatrix> PARSER =
        new com.google.protobuf.AbstractParser<DMatrix>() {
      public DMatrix parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DMatrix(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DMatrix> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>required int64 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    // repeated .protobuf.DRow row = 2;
    public static final int ROW_FIELD_NUMBER = 2;
    private java.util.List<protobuf.MatrixDouble.DRow> row_;
    /**
     * <code>repeated .protobuf.DRow row = 2;</code>
     */
    public java.util.List<protobuf.MatrixDouble.DRow> getRowList() {
      return row_;
    }
    /**
     * <code>repeated .protobuf.DRow row = 2;</code>
     */
    public java.util.List<? extends protobuf.MatrixDouble.DRowOrBuilder> 
        getRowOrBuilderList() {
      return row_;
    }
    /**
     * <code>repeated .protobuf.DRow row = 2;</code>
     */
    public int getRowCount() {
      return row_.size();
    }
    /**
     * <code>repeated .protobuf.DRow row = 2;</code>
     */
    public protobuf.MatrixDouble.DRow getRow(int index) {
      return row_.get(index);
    }
    /**
     * <code>repeated .protobuf.DRow row = 2;</code>
     */
    public protobuf.MatrixDouble.DRowOrBuilder getRowOrBuilder(
        int index) {
      return row_.get(index);
    }

    private void initFields() {
      id_ = 0L;
      row_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getRowCount(); i++) {
        if (!getRow(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, id_);
      }
      for (int i = 0; i < row_.size(); i++) {
        output.writeMessage(2, row_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      for (int i = 0; i < row_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, row_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protobuf.MatrixDouble.DMatrix parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.MatrixDouble.DMatrix parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.MatrixDouble.DMatrix parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.MatrixDouble.DMatrix parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.MatrixDouble.DMatrix parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.MatrixDouble.DMatrix parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protobuf.MatrixDouble.DMatrix parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protobuf.MatrixDouble.DMatrix parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protobuf.MatrixDouble.DMatrix parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.MatrixDouble.DMatrix parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobuf.MatrixDouble.DMatrix prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.DMatrix}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protobuf.MatrixDouble.DMatrixOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.MatrixDouble.internal_static_protobuf_DMatrix_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.MatrixDouble.internal_static_protobuf_DMatrix_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.MatrixDouble.DMatrix.class, protobuf.MatrixDouble.DMatrix.Builder.class);
      }

      // Construct using protobuf.MatrixDouble.DMatrix.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRowFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (rowBuilder_ == null) {
          row_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          rowBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.MatrixDouble.internal_static_protobuf_DMatrix_descriptor;
      }

      public protobuf.MatrixDouble.DMatrix getDefaultInstanceForType() {
        return protobuf.MatrixDouble.DMatrix.getDefaultInstance();
      }

      public protobuf.MatrixDouble.DMatrix build() {
        protobuf.MatrixDouble.DMatrix result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.MatrixDouble.DMatrix buildPartial() {
        protobuf.MatrixDouble.DMatrix result = new protobuf.MatrixDouble.DMatrix(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (rowBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            row_ = java.util.Collections.unmodifiableList(row_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.row_ = row_;
        } else {
          result.row_ = rowBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.MatrixDouble.DMatrix) {
          return mergeFrom((protobuf.MatrixDouble.DMatrix)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.MatrixDouble.DMatrix other) {
        if (other == protobuf.MatrixDouble.DMatrix.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (rowBuilder_ == null) {
          if (!other.row_.isEmpty()) {
            if (row_.isEmpty()) {
              row_ = other.row_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureRowIsMutable();
              row_.addAll(other.row_);
            }
            onChanged();
          }
        } else {
          if (!other.row_.isEmpty()) {
            if (rowBuilder_.isEmpty()) {
              rowBuilder_.dispose();
              rowBuilder_ = null;
              row_ = other.row_;
              bitField0_ = (bitField0_ & ~0x00000002);
              rowBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getRowFieldBuilder() : null;
            } else {
              rowBuilder_.addAllMessages(other.row_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        for (int i = 0; i < getRowCount(); i++) {
          if (!getRow(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.MatrixDouble.DMatrix parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.MatrixDouble.DMatrix) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 id = 1;
      private long id_ ;
      /**
       * <code>required int64 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      // repeated .protobuf.DRow row = 2;
      private java.util.List<protobuf.MatrixDouble.DRow> row_ =
        java.util.Collections.emptyList();
      private void ensureRowIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          row_ = new java.util.ArrayList<protobuf.MatrixDouble.DRow>(row_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          protobuf.MatrixDouble.DRow, protobuf.MatrixDouble.DRow.Builder, protobuf.MatrixDouble.DRowOrBuilder> rowBuilder_;

      /**
       * <code>repeated .protobuf.DRow row = 2;</code>
       */
      public java.util.List<protobuf.MatrixDouble.DRow> getRowList() {
        if (rowBuilder_ == null) {
          return java.util.Collections.unmodifiableList(row_);
        } else {
          return rowBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protobuf.DRow row = 2;</code>
       */
      public int getRowCount() {
        if (rowBuilder_ == null) {
          return row_.size();
        } else {
          return rowBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protobuf.DRow row = 2;</code>
       */
      public protobuf.MatrixDouble.DRow getRow(int index) {
        if (rowBuilder_ == null) {
          return row_.get(index);
        } else {
          return rowBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protobuf.DRow row = 2;</code>
       */
      public Builder setRow(
          int index, protobuf.MatrixDouble.DRow value) {
        if (rowBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRowIsMutable();
          row_.set(index, value);
          onChanged();
        } else {
          rowBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.DRow row = 2;</code>
       */
      public Builder setRow(
          int index, protobuf.MatrixDouble.DRow.Builder builderForValue) {
        if (rowBuilder_ == null) {
          ensureRowIsMutable();
          row_.set(index, builderForValue.build());
          onChanged();
        } else {
          rowBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.DRow row = 2;</code>
       */
      public Builder addRow(protobuf.MatrixDouble.DRow value) {
        if (rowBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRowIsMutable();
          row_.add(value);
          onChanged();
        } else {
          rowBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.DRow row = 2;</code>
       */
      public Builder addRow(
          int index, protobuf.MatrixDouble.DRow value) {
        if (rowBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRowIsMutable();
          row_.add(index, value);
          onChanged();
        } else {
          rowBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.DRow row = 2;</code>
       */
      public Builder addRow(
          protobuf.MatrixDouble.DRow.Builder builderForValue) {
        if (rowBuilder_ == null) {
          ensureRowIsMutable();
          row_.add(builderForValue.build());
          onChanged();
        } else {
          rowBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.DRow row = 2;</code>
       */
      public Builder addRow(
          int index, protobuf.MatrixDouble.DRow.Builder builderForValue) {
        if (rowBuilder_ == null) {
          ensureRowIsMutable();
          row_.add(index, builderForValue.build());
          onChanged();
        } else {
          rowBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.DRow row = 2;</code>
       */
      public Builder addAllRow(
          java.lang.Iterable<? extends protobuf.MatrixDouble.DRow> values) {
        if (rowBuilder_ == null) {
          ensureRowIsMutable();
          super.addAll(values, row_);
          onChanged();
        } else {
          rowBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.DRow row = 2;</code>
       */
      public Builder clearRow() {
        if (rowBuilder_ == null) {
          row_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          rowBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.DRow row = 2;</code>
       */
      public Builder removeRow(int index) {
        if (rowBuilder_ == null) {
          ensureRowIsMutable();
          row_.remove(index);
          onChanged();
        } else {
          rowBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.DRow row = 2;</code>
       */
      public protobuf.MatrixDouble.DRow.Builder getRowBuilder(
          int index) {
        return getRowFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protobuf.DRow row = 2;</code>
       */
      public protobuf.MatrixDouble.DRowOrBuilder getRowOrBuilder(
          int index) {
        if (rowBuilder_ == null) {
          return row_.get(index);  } else {
          return rowBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protobuf.DRow row = 2;</code>
       */
      public java.util.List<? extends protobuf.MatrixDouble.DRowOrBuilder> 
           getRowOrBuilderList() {
        if (rowBuilder_ != null) {
          return rowBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(row_);
        }
      }
      /**
       * <code>repeated .protobuf.DRow row = 2;</code>
       */
      public protobuf.MatrixDouble.DRow.Builder addRowBuilder() {
        return getRowFieldBuilder().addBuilder(
            protobuf.MatrixDouble.DRow.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.DRow row = 2;</code>
       */
      public protobuf.MatrixDouble.DRow.Builder addRowBuilder(
          int index) {
        return getRowFieldBuilder().addBuilder(
            index, protobuf.MatrixDouble.DRow.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.DRow row = 2;</code>
       */
      public java.util.List<protobuf.MatrixDouble.DRow.Builder> 
           getRowBuilderList() {
        return getRowFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          protobuf.MatrixDouble.DRow, protobuf.MatrixDouble.DRow.Builder, protobuf.MatrixDouble.DRowOrBuilder> 
          getRowFieldBuilder() {
        if (rowBuilder_ == null) {
          rowBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              protobuf.MatrixDouble.DRow, protobuf.MatrixDouble.DRow.Builder, protobuf.MatrixDouble.DRowOrBuilder>(
                  row_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          row_ = null;
        }
        return rowBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.DMatrix)
    }

    static {
      defaultInstance = new DMatrix(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuf.DMatrix)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_DRow_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_DRow_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_DMatrix_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_DMatrix_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022matrixDouble.proto\022\010protobuf\"#\n\004DRow\022\016" +
      "\n\006rowNum\030\001 \002(\003\022\013\n\003num\030\002 \003(\001\"2\n\007DMatrix\022\n" +
      "\n\002id\030\001 \002(\003\022\033\n\003row\030\002 \003(\0132\016.protobuf.DRow"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protobuf_DRow_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protobuf_DRow_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobuf_DRow_descriptor,
              new java.lang.String[] { "RowNum", "Num", });
          internal_static_protobuf_DMatrix_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_protobuf_DMatrix_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobuf_DMatrix_descriptor,
              new java.lang.String[] { "Id", "Row", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
