// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: matrixLong.proto

package protobuf;

public final class MatrixLong {
  private MatrixLong() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RowOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required sint64 rowNum = 1;
    /**
     * <code>required sint64 rowNum = 1;</code>
     */
    boolean hasRowNum();
    /**
     * <code>required sint64 rowNum = 1;</code>
     */
    long getRowNum();

    // repeated sint64 num = 2;
    /**
     * <code>repeated sint64 num = 2;</code>
     */
    java.util.List<java.lang.Long> getNumList();
    /**
     * <code>repeated sint64 num = 2;</code>
     */
    int getNumCount();
    /**
     * <code>repeated sint64 num = 2;</code>
     */
    long getNum(int index);
  }
  /**
   * Protobuf type {@code protobuf.Row}
   */
  public static final class Row extends
      com.google.protobuf.GeneratedMessage
      implements RowOrBuilder {
    // Use Row.newBuilder() to construct.
    private Row(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Row(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Row defaultInstance;
    public static Row getDefaultInstance() {
      return defaultInstance;
    }

    public Row getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Row(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              rowNum_ = input.readSInt64();
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                num_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000002;
              }
              num_.add(input.readSInt64());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                num_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                num_.add(input.readSInt64());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          num_ = java.util.Collections.unmodifiableList(num_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.MatrixLong.internal_static_protobuf_Row_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.MatrixLong.internal_static_protobuf_Row_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.MatrixLong.Row.class, protobuf.MatrixLong.Row.Builder.class);
    }

    public static com.google.protobuf.Parser<Row> PARSER =
        new com.google.protobuf.AbstractParser<Row>() {
      public Row parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Row(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Row> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required sint64 rowNum = 1;
    public static final int ROWNUM_FIELD_NUMBER = 1;
    private long rowNum_;
    /**
     * <code>required sint64 rowNum = 1;</code>
     */
    public boolean hasRowNum() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required sint64 rowNum = 1;</code>
     */
    public long getRowNum() {
      return rowNum_;
    }

    // repeated sint64 num = 2;
    public static final int NUM_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Long> num_;
    /**
     * <code>repeated sint64 num = 2;</code>
     */
    public java.util.List<java.lang.Long>
        getNumList() {
      return num_;
    }
    /**
     * <code>repeated sint64 num = 2;</code>
     */
    public int getNumCount() {
      return num_.size();
    }
    /**
     * <code>repeated sint64 num = 2;</code>
     */
    public long getNum(int index) {
      return num_.get(index);
    }

    private void initFields() {
      rowNum_ = 0L;
      num_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasRowNum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeSInt64(1, rowNum_);
      }
      for (int i = 0; i < num_.size(); i++) {
        output.writeSInt64(2, num_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(1, rowNum_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < num_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeSInt64SizeNoTag(num_.get(i));
        }
        size += dataSize;
        size += 1 * getNumList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protobuf.MatrixLong.Row parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.MatrixLong.Row parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.MatrixLong.Row parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.MatrixLong.Row parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.MatrixLong.Row parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.MatrixLong.Row parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protobuf.MatrixLong.Row parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protobuf.MatrixLong.Row parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protobuf.MatrixLong.Row parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.MatrixLong.Row parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobuf.MatrixLong.Row prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.Row}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protobuf.MatrixLong.RowOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.MatrixLong.internal_static_protobuf_Row_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.MatrixLong.internal_static_protobuf_Row_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.MatrixLong.Row.class, protobuf.MatrixLong.Row.Builder.class);
      }

      // Construct using protobuf.MatrixLong.Row.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        rowNum_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        num_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.MatrixLong.internal_static_protobuf_Row_descriptor;
      }

      public protobuf.MatrixLong.Row getDefaultInstanceForType() {
        return protobuf.MatrixLong.Row.getDefaultInstance();
      }

      public protobuf.MatrixLong.Row build() {
        protobuf.MatrixLong.Row result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.MatrixLong.Row buildPartial() {
        protobuf.MatrixLong.Row result = new protobuf.MatrixLong.Row(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.rowNum_ = rowNum_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          num_ = java.util.Collections.unmodifiableList(num_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.num_ = num_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.MatrixLong.Row) {
          return mergeFrom((protobuf.MatrixLong.Row)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.MatrixLong.Row other) {
        if (other == protobuf.MatrixLong.Row.getDefaultInstance()) return this;
        if (other.hasRowNum()) {
          setRowNum(other.getRowNum());
        }
        if (!other.num_.isEmpty()) {
          if (num_.isEmpty()) {
            num_ = other.num_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureNumIsMutable();
            num_.addAll(other.num_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRowNum()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.MatrixLong.Row parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.MatrixLong.Row) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required sint64 rowNum = 1;
      private long rowNum_ ;
      /**
       * <code>required sint64 rowNum = 1;</code>
       */
      public boolean hasRowNum() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required sint64 rowNum = 1;</code>
       */
      public long getRowNum() {
        return rowNum_;
      }
      /**
       * <code>required sint64 rowNum = 1;</code>
       */
      public Builder setRowNum(long value) {
        bitField0_ |= 0x00000001;
        rowNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required sint64 rowNum = 1;</code>
       */
      public Builder clearRowNum() {
        bitField0_ = (bitField0_ & ~0x00000001);
        rowNum_ = 0L;
        onChanged();
        return this;
      }

      // repeated sint64 num = 2;
      private java.util.List<java.lang.Long> num_ = java.util.Collections.emptyList();
      private void ensureNumIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          num_ = new java.util.ArrayList<java.lang.Long>(num_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated sint64 num = 2;</code>
       */
      public java.util.List<java.lang.Long>
          getNumList() {
        return java.util.Collections.unmodifiableList(num_);
      }
      /**
       * <code>repeated sint64 num = 2;</code>
       */
      public int getNumCount() {
        return num_.size();
      }
      /**
       * <code>repeated sint64 num = 2;</code>
       */
      public long getNum(int index) {
        return num_.get(index);
      }
      /**
       * <code>repeated sint64 num = 2;</code>
       */
      public Builder setNum(
          int index, long value) {
        ensureNumIsMutable();
        num_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated sint64 num = 2;</code>
       */
      public Builder addNum(long value) {
        ensureNumIsMutable();
        num_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated sint64 num = 2;</code>
       */
      public Builder addAllNum(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureNumIsMutable();
        super.addAll(values, num_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated sint64 num = 2;</code>
       */
      public Builder clearNum() {
        num_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.Row)
    }

    static {
      defaultInstance = new Row(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuf.Row)
  }

  public interface MatrixOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required sint64 id = 1;
    /**
     * <code>required sint64 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required sint64 id = 1;</code>
     */
    long getId();

    // repeated .protobuf.Row row = 2;
    /**
     * <code>repeated .protobuf.Row row = 2;</code>
     */
    java.util.List<protobuf.MatrixLong.Row> 
        getRowList();
    /**
     * <code>repeated .protobuf.Row row = 2;</code>
     */
    protobuf.MatrixLong.Row getRow(int index);
    /**
     * <code>repeated .protobuf.Row row = 2;</code>
     */
    int getRowCount();
    /**
     * <code>repeated .protobuf.Row row = 2;</code>
     */
    java.util.List<? extends protobuf.MatrixLong.RowOrBuilder> 
        getRowOrBuilderList();
    /**
     * <code>repeated .protobuf.Row row = 2;</code>
     */
    protobuf.MatrixLong.RowOrBuilder getRowOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code protobuf.Matrix}
   */
  public static final class Matrix extends
      com.google.protobuf.GeneratedMessage
      implements MatrixOrBuilder {
    // Use Matrix.newBuilder() to construct.
    private Matrix(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Matrix(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Matrix defaultInstance;
    public static Matrix getDefaultInstance() {
      return defaultInstance;
    }

    public Matrix getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Matrix(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readSInt64();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                row_ = new java.util.ArrayList<protobuf.MatrixLong.Row>();
                mutable_bitField0_ |= 0x00000002;
              }
              row_.add(input.readMessage(protobuf.MatrixLong.Row.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          row_ = java.util.Collections.unmodifiableList(row_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.MatrixLong.internal_static_protobuf_Matrix_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.MatrixLong.internal_static_protobuf_Matrix_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.MatrixLong.Matrix.class, protobuf.MatrixLong.Matrix.Builder.class);
    }

    public static com.google.protobuf.Parser<Matrix> PARSER =
        new com.google.protobuf.AbstractParser<Matrix>() {
      public Matrix parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Matrix(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Matrix> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required sint64 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>required sint64 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required sint64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    // repeated .protobuf.Row row = 2;
    public static final int ROW_FIELD_NUMBER = 2;
    private java.util.List<protobuf.MatrixLong.Row> row_;
    /**
     * <code>repeated .protobuf.Row row = 2;</code>
     */
    public java.util.List<protobuf.MatrixLong.Row> getRowList() {
      return row_;
    }
    /**
     * <code>repeated .protobuf.Row row = 2;</code>
     */
    public java.util.List<? extends protobuf.MatrixLong.RowOrBuilder> 
        getRowOrBuilderList() {
      return row_;
    }
    /**
     * <code>repeated .protobuf.Row row = 2;</code>
     */
    public int getRowCount() {
      return row_.size();
    }
    /**
     * <code>repeated .protobuf.Row row = 2;</code>
     */
    public protobuf.MatrixLong.Row getRow(int index) {
      return row_.get(index);
    }
    /**
     * <code>repeated .protobuf.Row row = 2;</code>
     */
    public protobuf.MatrixLong.RowOrBuilder getRowOrBuilder(
        int index) {
      return row_.get(index);
    }

    private void initFields() {
      id_ = 0L;
      row_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getRowCount(); i++) {
        if (!getRow(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeSInt64(1, id_);
      }
      for (int i = 0; i < row_.size(); i++) {
        output.writeMessage(2, row_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(1, id_);
      }
      for (int i = 0; i < row_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, row_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protobuf.MatrixLong.Matrix parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.MatrixLong.Matrix parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.MatrixLong.Matrix parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.MatrixLong.Matrix parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.MatrixLong.Matrix parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.MatrixLong.Matrix parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protobuf.MatrixLong.Matrix parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protobuf.MatrixLong.Matrix parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protobuf.MatrixLong.Matrix parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.MatrixLong.Matrix parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobuf.MatrixLong.Matrix prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.Matrix}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protobuf.MatrixLong.MatrixOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.MatrixLong.internal_static_protobuf_Matrix_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.MatrixLong.internal_static_protobuf_Matrix_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.MatrixLong.Matrix.class, protobuf.MatrixLong.Matrix.Builder.class);
      }

      // Construct using protobuf.MatrixLong.Matrix.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRowFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (rowBuilder_ == null) {
          row_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          rowBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.MatrixLong.internal_static_protobuf_Matrix_descriptor;
      }

      public protobuf.MatrixLong.Matrix getDefaultInstanceForType() {
        return protobuf.MatrixLong.Matrix.getDefaultInstance();
      }

      public protobuf.MatrixLong.Matrix build() {
        protobuf.MatrixLong.Matrix result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.MatrixLong.Matrix buildPartial() {
        protobuf.MatrixLong.Matrix result = new protobuf.MatrixLong.Matrix(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (rowBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            row_ = java.util.Collections.unmodifiableList(row_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.row_ = row_;
        } else {
          result.row_ = rowBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.MatrixLong.Matrix) {
          return mergeFrom((protobuf.MatrixLong.Matrix)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.MatrixLong.Matrix other) {
        if (other == protobuf.MatrixLong.Matrix.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (rowBuilder_ == null) {
          if (!other.row_.isEmpty()) {
            if (row_.isEmpty()) {
              row_ = other.row_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureRowIsMutable();
              row_.addAll(other.row_);
            }
            onChanged();
          }
        } else {
          if (!other.row_.isEmpty()) {
            if (rowBuilder_.isEmpty()) {
              rowBuilder_.dispose();
              rowBuilder_ = null;
              row_ = other.row_;
              bitField0_ = (bitField0_ & ~0x00000002);
              rowBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getRowFieldBuilder() : null;
            } else {
              rowBuilder_.addAllMessages(other.row_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        for (int i = 0; i < getRowCount(); i++) {
          if (!getRow(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.MatrixLong.Matrix parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.MatrixLong.Matrix) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required sint64 id = 1;
      private long id_ ;
      /**
       * <code>required sint64 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required sint64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>required sint64 id = 1;</code>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required sint64 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      // repeated .protobuf.Row row = 2;
      private java.util.List<protobuf.MatrixLong.Row> row_ =
        java.util.Collections.emptyList();
      private void ensureRowIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          row_ = new java.util.ArrayList<protobuf.MatrixLong.Row>(row_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          protobuf.MatrixLong.Row, protobuf.MatrixLong.Row.Builder, protobuf.MatrixLong.RowOrBuilder> rowBuilder_;

      /**
       * <code>repeated .protobuf.Row row = 2;</code>
       */
      public java.util.List<protobuf.MatrixLong.Row> getRowList() {
        if (rowBuilder_ == null) {
          return java.util.Collections.unmodifiableList(row_);
        } else {
          return rowBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protobuf.Row row = 2;</code>
       */
      public int getRowCount() {
        if (rowBuilder_ == null) {
          return row_.size();
        } else {
          return rowBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protobuf.Row row = 2;</code>
       */
      public protobuf.MatrixLong.Row getRow(int index) {
        if (rowBuilder_ == null) {
          return row_.get(index);
        } else {
          return rowBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protobuf.Row row = 2;</code>
       */
      public Builder setRow(
          int index, protobuf.MatrixLong.Row value) {
        if (rowBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRowIsMutable();
          row_.set(index, value);
          onChanged();
        } else {
          rowBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Row row = 2;</code>
       */
      public Builder setRow(
          int index, protobuf.MatrixLong.Row.Builder builderForValue) {
        if (rowBuilder_ == null) {
          ensureRowIsMutable();
          row_.set(index, builderForValue.build());
          onChanged();
        } else {
          rowBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Row row = 2;</code>
       */
      public Builder addRow(protobuf.MatrixLong.Row value) {
        if (rowBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRowIsMutable();
          row_.add(value);
          onChanged();
        } else {
          rowBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Row row = 2;</code>
       */
      public Builder addRow(
          int index, protobuf.MatrixLong.Row value) {
        if (rowBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRowIsMutable();
          row_.add(index, value);
          onChanged();
        } else {
          rowBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Row row = 2;</code>
       */
      public Builder addRow(
          protobuf.MatrixLong.Row.Builder builderForValue) {
        if (rowBuilder_ == null) {
          ensureRowIsMutable();
          row_.add(builderForValue.build());
          onChanged();
        } else {
          rowBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Row row = 2;</code>
       */
      public Builder addRow(
          int index, protobuf.MatrixLong.Row.Builder builderForValue) {
        if (rowBuilder_ == null) {
          ensureRowIsMutable();
          row_.add(index, builderForValue.build());
          onChanged();
        } else {
          rowBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Row row = 2;</code>
       */
      public Builder addAllRow(
          java.lang.Iterable<? extends protobuf.MatrixLong.Row> values) {
        if (rowBuilder_ == null) {
          ensureRowIsMutable();
          super.addAll(values, row_);
          onChanged();
        } else {
          rowBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Row row = 2;</code>
       */
      public Builder clearRow() {
        if (rowBuilder_ == null) {
          row_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          rowBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Row row = 2;</code>
       */
      public Builder removeRow(int index) {
        if (rowBuilder_ == null) {
          ensureRowIsMutable();
          row_.remove(index);
          onChanged();
        } else {
          rowBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Row row = 2;</code>
       */
      public protobuf.MatrixLong.Row.Builder getRowBuilder(
          int index) {
        return getRowFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protobuf.Row row = 2;</code>
       */
      public protobuf.MatrixLong.RowOrBuilder getRowOrBuilder(
          int index) {
        if (rowBuilder_ == null) {
          return row_.get(index);  } else {
          return rowBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protobuf.Row row = 2;</code>
       */
      public java.util.List<? extends protobuf.MatrixLong.RowOrBuilder> 
           getRowOrBuilderList() {
        if (rowBuilder_ != null) {
          return rowBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(row_);
        }
      }
      /**
       * <code>repeated .protobuf.Row row = 2;</code>
       */
      public protobuf.MatrixLong.Row.Builder addRowBuilder() {
        return getRowFieldBuilder().addBuilder(
            protobuf.MatrixLong.Row.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.Row row = 2;</code>
       */
      public protobuf.MatrixLong.Row.Builder addRowBuilder(
          int index) {
        return getRowFieldBuilder().addBuilder(
            index, protobuf.MatrixLong.Row.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.Row row = 2;</code>
       */
      public java.util.List<protobuf.MatrixLong.Row.Builder> 
           getRowBuilderList() {
        return getRowFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          protobuf.MatrixLong.Row, protobuf.MatrixLong.Row.Builder, protobuf.MatrixLong.RowOrBuilder> 
          getRowFieldBuilder() {
        if (rowBuilder_ == null) {
          rowBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              protobuf.MatrixLong.Row, protobuf.MatrixLong.Row.Builder, protobuf.MatrixLong.RowOrBuilder>(
                  row_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          row_ = null;
        }
        return rowBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.Matrix)
    }

    static {
      defaultInstance = new Matrix(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuf.Matrix)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_Row_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_Row_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_Matrix_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_Matrix_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020matrixLong.proto\022\010protobuf\"\"\n\003Row\022\016\n\006r" +
      "owNum\030\001 \002(\022\022\013\n\003num\030\002 \003(\022\"0\n\006Matrix\022\n\n\002id" +
      "\030\001 \002(\022\022\032\n\003row\030\002 \003(\0132\r.protobuf.Row"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protobuf_Row_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protobuf_Row_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobuf_Row_descriptor,
              new java.lang.String[] { "RowNum", "Num", });
          internal_static_protobuf_Matrix_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_protobuf_Matrix_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobuf_Matrix_descriptor,
              new java.lang.String[] { "Id", "Row", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
